name: PR Gate Branch name test

on:
  pull_request:
    branches:
      - main
      - ef-prod-na

jobs:
  API-Access-PR-Gate-Validation:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        env:
          BASE_REF: ${{ github.base_ref }}
          HEAD_REF: ${{ github.head_ref }}
        run: |
          echo "Base ref: $BASE_REF"
          echo "Head ref: $HEAD_REF"