name: Run Python Hello (all envs)

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  run-python-job:
    strategy:
      fail-fast: false
      matrix:
        env_name: [tst, psr, prod-na, prod-eu]

    runs-on: self-hosted

    env:
      RUNNER_TOOL_CACHE: ${{ github.workspace }}/_toolcache
      RUNNER_TEMP: ${{ github.workspace }}/_temp

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prep tool cache dirs (self-hosted fix)
        run: |
          mkdir -p "${RUNNER_TOOL_CACHE}"
          mkdir -p "${RUNNER_TEMP}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Running for ${{ matrix.env_name }}?
        run: |
          echo "Running job for environment: ${{ matrix.env_name }}"

      - name: Run hello script
        run: |
          python hello.py "${{ matrix.env_name }}"
